### PR TITLE
Add dbd keywords used by epics base dbds

### PR DESCRIPTION
**Pull request by hanak**
Solves #28 

**Purpose**
EPICS base DBDs do not highlight all keywords.

**Solution**
* Added field-related keywords (e.g. pp) in the DBD file.
* Added enums with field-related keywords in a DBD file.
* Corrected highlighting of escaped characters in a string.
* Extended test.dbd file with examples.

### CODE REVIEW

**Comment by hanak** [comment]
Please, review.

Please, close #28 once this is merged.

I am not able to predict when I will be able to contribute more. Therefore, if you feel the time is right for the release 0.0.11, feel free to release it.

Thank you.

**Comment by hanak** [comment]
Is there anything which is missing in this pull request?

**Comment by NSenaud** [comment]
Hi @hanak , sorry I missed last Github emails, as usual I request @vnadot assistance to review the PR.

**Comment by vnadot** [comment]
Hi @hanak ,
I guess it could be closed now ?
Cheers,

**Comment by hanak** [comment]
Hi @vnadot,
I agree.
Thank you.

**Pull request merged**
